const fs = require('fs')
const path = require('path')
const LRU = require('lru-cache')
const url = require('url')
const express = require('express')
const favicon = require('serve-favicon')
const compression = require('compression')
const resolve = file => path.resolve(__dirname, file)
const { createBundleRenderer } = require('vue-server-renderer')
const { initJsCss, initMeta } = require('./config/head')
const { setCookie, getCookie, delCookie, parseCookie, keys } = require('./src/util/cookie.js')

const isProd = process.env.NODE_ENV === 'production'
const useMicroCache = process.env.MICRO_CACHE !== 'false'
const serverInfo =
  `express/${require('express/package.json').version} ` +
  `vue-server-renderer/${require('vue-server-renderer/package.json').version}`

const app = express()

const template = fs.readFileSync(resolve('./index.html'), 'utf-8')

function createRenderer (bundle, options) {
  // https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/README.md#why-use-bundlerenderer
  return createBundleRenderer(bundle, Object.assign(options, {
    template,
    // for component caching
    cache: LRU({
      max: 1000,
      maxAge: 1000 * 60 * 15
    }),
    // this is only needed when vue-server-renderer is npm-linked
    basedir: resolve('./dist'),
    // recommended for performance
    runInNewContext: false
  }))
}

let renderer
let readyPromise
if (isProd) {
  // In production: create server renderer using built server bundle.
  // The server bundle is generated by vue-ssr-webpack-plugin.
  const bundle = require('./dist/js/vue-ssr-server-bundle.json')
  // The client manifests are optional, but it allows the renderer
  // to automatically infer preload/prefetch links and directly add <script>
  // tags for any async chunks used during render, avoiding waterfall requests.
  // template = fs.readFileSync(resolve('./dist/index.html'), 'utf-8')
  const clientManifest = require('./dist/js/vue-ssr-client-manifest.json')
  renderer = createRenderer(bundle, {
    clientManifest
  })
} else {
  // In development: setup the dev server with watch and hot-reload,
  // and create a new renderer on bundle / index template update.
  // template = fs.readFileSync(resolve('./src/index.template.html'), 'utf-8')
  readyPromise = require('./build/setup-dev-server')(app, (bundle, options) => {
    renderer = createRenderer(bundle, options)
  })
}

const serve = (path, cache) => express.static(resolve(path), {
  maxAge: cache && isProd ? 60 * 60 * 24 * 30 : 0
})

app.use(compression({ threshold: 0 }))
app.use(favicon('./public/logo-48.png'))
app.use('/dist', serve('./dist', true))
app.use('/public', serve('./public', true))
app.use('/manifest.json', serve('./manifest.json', true))
app.use('/service-worker.js', serve('./dist/service-worker.js'))

// 1-second microcache.
// https://www.nginx.com/blog/benefits-of-microcaching-nginx/
const microCache = LRU({
  max: 100,
  maxAge: 1000
})

// since this app has no user-specific content, every page is micro-cacheable.
// if your app involves user-specific content, you need to implement custom
// logic to determine whether a request is cacheable based on its url and
// headers.
const isCacheable = req => useMicroCache

function render (req, res) {
  const s = Date.now()

  res.setHeader("Content-Type", "text/html")
  res.setHeader("Server", serverInfo)

  const handleError = err => {
    if (err && err.code === 404) {
      res.status(404).end('404 | Page Not Found')
    } else {
      // Render Error Page or Redirect
      res.status(500).end('500 | Internal Server Error')
      console.error(`error during render : ${req.url}`)
      console.error(err.stack)
    }
  }

  const cacheable = isCacheable(req)
  if (cacheable) {
    const hit = microCache.get(req.url)
    if (hit) {
      if (!isProd) {
        console.log(`cache hit!`)
      }
      return res.end(hit)
    }
  }
  var _cookies = req.headers.cookie
  var cookies = 'asdfasdfasdfasdf'
  const context = {
    title: '江苏明美五金', // default title
    url: req.url,
    cookies: cookies
  }
  //开始渲染
  renderer.renderToString(context, (err, html) => {
    /*var newState = JSON.parse(JSON.stringify(context.state))
    var jsContentStr
    newState.res = ''
    console.log('context---------------------=================---------------------------')
    console.log(newState)
    console.log('context---------------------=================---------------------------')
    var infoStr = 'window.__INITIAL_STATE__=' + JSON.stringify(newState)
    var jsInsertStr = '<script name="jsInfo"/>'
    var jsStateStr = '<script>' + infoStr + '</script>'
    html = html.replace(jsInsertStr, jsStateStr)*/
    if (err) {
      return handleError(err)
    }
    //meta
    const metaInsertStr = "<meta name='metaInfo'>"
    var metaContent = initMeta(context.meta)
    html = html.replace(metaInsertStr, metaContent)

    //css js
    var cssInsertStr = '<link name=\'cssInfo\'/>'
    //console.log('url----------------------------------------url')
    var arran = url.parse(req.url).pathname.split('/')
    var num
    if (arran.length == 4) {
      //console.log(arran[2])
      num = arran[2]
    }
    //console.log('url----------------------------------------url')
    var {jsContent, cssContent} = initJsCss(url.parse(req.url).pathname,num)
    html = html.replace(cssInsertStr, cssContent)
    var jsStr = html.match(/<link rel="preload".*<link rel=.*?>/g)
    html = html.replace(jsStr, jsContent)
    res.end(html)
    if (cacheable) {
      microCache.set(req.url, html)
    }
    if (!isProd) {
      console.log(`whole request: ${Date.now() - s}ms`)
    }
  })
}

app.get('*', isProd ? render : (req, res) => {
  readyPromise.then(() => render(req, res))
})

const port = process.env.PORT || 8060
app.listen(port, () => {
  console.log(`server started at localhost:${port}`)
})
