/**
 * Created by dell on 2017/2/16.
 */
// 详情页
export const SET_HEAD_BANNER = 'SET_HEAD_BANNER'
export const SET_THREE_RECOMMEND = 'SET_THREE_RECOMMEND'
export const SET_NEW_PRODUCT = 'SET_NEW_PRODUCT'
export const SET_HOT_SELL = 'SET_HOT_SELL'
export const SET_BEST_PRO = 'SET_BEST_PRO'
export const SET_SERVER_PRO = 'SET_SERVER_PRO'
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA'
export const SET_PRODUCT_SINGLE = 'SET_PRODUCT_SINGLE'
export const SET_ADDSHOP_DATA = 'SET_ADDSHOP_DATA'
export const SET_GET_SHOPCAR = 'SET_GET_SHOPCAR'
export const GOODS_REDUCE_LIST = 'GOODS_REDUCE_LIST'
export const GOODS_ADD_LIST = 'GOODS_ADD_LIST'
export const POST_PERSON_INFO = 'POST_PERSON_INFO'
export const GET_PERSON_INFO = 'GET_PERSON_INFO'
export const POST_SUBMITORDER = 'POST_SUBMITORDER'
export const GET_RECOMMAND_INFO = 'GET_RECOMMAND_INFO'
